### ISSUE TITLE
Getting paid

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/geotargets-isc-proposal#1]
One of the quirks about RConsortium ISC funding is that they'll only pay one person. When I got funding for `webchem`, Tamás was the "PI" and I was a "sub-contractor".  We split the work and the award equally, but on paper he invoiced the RConsortium and I had to invoice him (and then he wrote me a check or venmo'd me or something like that).  Now that I work at a university, I suspect it's a bit more complicated.  With the ISC funding for `volcalc`, that had to go through our grants office.  I'm not sure what the situation is at your place of work, @njtierney.  I'll ask our grants person if one option or the other is easiest on my end.

**Comment by njtierney** [comment]
It's a bit tricky at my work as well - I'm happy to not receive funding and to help provide in-kind/supervision?

**Comment by Aariq** [comment]
Still waiting to hear back from my grants person to see what the process is like for paying external/international contractors

**Comment by Aariq** [comment]
Turns out RConsortium can pay us separately afterall
